export interface SquareType {
    id:string,
    pic:string,
    letter:string,
    value:number,
    selected:boolean,
    inside:boolean
}
export const DefaultSquares : SquareType[] = [
    {
        id:'00',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false
    },    
    {
        id:'01',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false

    },    
    {
        id:'02',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false

    },
    {
        id:'03',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false

    },
    {
        id:'04',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false

    },
    {
        id:'05',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false

    },
    {
        id:'06',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false

    },
    {
        id:'10',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false

    },    
    {
        id:'11',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true
    },    
    {
        id:'12',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'13',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'14',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'15',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'16',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false
    },
    {
        id:'20',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false
    },    
    {
        id:'21',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },    
    {
        id:'22',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'23',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'24',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'25',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'26',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false
    },
    {
        id:'30',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false
    },    
    {
        id:'31',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },    
    {
        id:'32',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'33',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'34',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'35',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'36',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false
    },
    {
        id:'40',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false
    },    
    {
        id:'41',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },    
    {
        id:'42',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'43',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'44',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'45',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'46',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false
    },
    {
        id:'50',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false
    },    
    {
        id:'51',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },    
    {
        id:'52',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'53',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'54',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'55',
        pic:'/wordokuImages/blank2.png',
        letter:'',
        value:0,
        selected:false,
        inside:true

    },
    {
        id:'56',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false
    },
    {
        id:'60',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false
    },    
    {
        id:'61',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false
    },    
    {
        id:'62',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false
    },
    {
        id:'63',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false
    },
    {
        id:'64',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false
    },
    {
        id:'65',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false
    },
    {
        id:'66',
        pic:'/wordokuImages/blank1.png',
        letter:'',
        value:0,
        selected:false,
        inside:false
    }
]